-- =============================================================================
-- DATABASE SCHEMA DESIGN FOR CAR DEALERSHIP INVENTORY SYSTEM (DAY 1)
-- =============================================================================

-- Enable extension for generating UUIDs if not already enabled (needed for database side, though we can generate them in Java)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. USERS TABLE
-- Stores user account information for authentication and role-based authorization.
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY,                                     -- UUID used to prevent enumeration attacks and preserve distributed system compatibility.
    name VARCHAR(100) NOT NULL,                              -- User's full name, restricted to 100 chars to save space.
    email VARCHAR(150) NOT NULL,                             -- Email used as username, unique, restricted to 150 chars.
    password VARCHAR(255) NOT NULL,                          -- BCrypt hashed password (always 60 chars, but 255 allows future hash algorithm changes).
    role VARCHAR(50) NOT NULL,                               -- User role: ROLE_USER, ROLE_ADMIN, etc.
    created_at TIMESTAMP NOT NULL,                           -- Auditing field: tracking creation timestamp.
    updated_at TIMESTAMP NOT NULL,                           -- Auditing field: tracking modification timestamp.
    CONSTRAINT uq_users_email UNIQUE (email)                 -- CONSTRAINT: Ensures no duplicate emails can register in the system.
);

-- INDEXES FOR USERS
-- Index on email is critical because we look up users by email during every login and authentication request.
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);


-- 2. VEHICLES TABLE
-- Stores the cars inventory of the dealership.
CREATE TABLE IF NOT EXISTS vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Auto-incrementing 64-bit integer, suitable for internal entities.
    make VARCHAR(100) NOT NULL,                              -- Car manufacturer (e.g. Tesla, Toyota).
    model VARCHAR(100) NOT NULL,                             -- Car model name (e.g. Model 3, Camry).
    category VARCHAR(100) NOT NULL,                          -- Vehicle category (e.g. Sedan, SUV, EV).
    price DECIMAL(12, 2) NOT NULL,                           -- Price with up to 10 digits for whole currency and 2 decimal points.
    quantity INTEGER NOT NULL,                               -- Quantity in stock.
    created_at TIMESTAMP NOT NULL,                           -- Auditing field: tracking creation timestamp.
    updated_at TIMESTAMP NOT NULL,                           -- Auditing field: tracking modification timestamp.
    CONSTRAINT chk_vehicles_price CHECK (price >= 0.00),     -- CONSTRAINT: Prevent negative car prices.
    CONSTRAINT chk_vehicles_quantity CHECK (quantity >= 0)   -- CONSTRAINT: Prevent negative inventory stock quantities.
);

-- INDEXES FOR VEHICLES
-- Indexes on make and model to speed up search/filter operations when buyers look for specific cars.
CREATE INDEX IF NOT EXISTS idx_vehicles_make_model ON vehicles(make, model);
CREATE INDEX IF NOT EXISTS idx_vehicles_category ON vehicles(category);
